name: qr_encrypted_access
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.3.0
  http: ^1.3.0
  cryptography: ^2.7.0
  qr_flutter: ^4.1.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/student_ids.json